这个表现就是下图

错误日志没有，也不报错

![](https://gitee.com/hxc8/images6/raw/master/img/202407182352705.jpg)

但是就是存储池没添加上。

后来发现是Django升级到2.2之后有些语法不兼容

需要把fs.data_pool = data_pool改为

fs.data_pool.set(data_pool) # 这里需要修改

位置为 vim /opt/vcfs/vcmp/web/vclusters/controllers/storage_fs/vcfs/file_system.py +111

重启vcmp就行了